/* eslint-disable */
import { mockIp, mockReqId } from '../../../utils/mock';
import i18n from '../../../i18n/index';


export const resp = {
  data: {
    pageNum: 1,
    pageSize: 10,
    totalCount: 51,
    states: {
      audit: 1,
      approved: 6,
      complete: 2,
      closed: 1,
    },
    dataList: [
      {
        buttonVOs: [
          {
            name: i18n.t('Modify tracking number'),
            primary: false,
            type: 4,
          },
          {
            name: i18n.t('View package shipping'),
            primary: false,
            type: 5,
          },
        ],
        saasId: '8888',
        storeId: '2591',
        uid: '88881046205',
        refundMethodList: [
          {
            refundMethodAmount: 99999,
            refundMethodName: 'WeChat Pay',
          },
          {
            refundMethodAmount: 100000,
            refundMethodName: i18n.t('Credit or debit card'),
          },
        ],
        createTime: '1596524705613',
        rights: {
          bizRightsStatus: 1,
          bizRightsStatusName: i18n.t('Refund and return'),
          createTime: '1596524705613',
          orderNo: '12313123123',
          refundAmount: 99999,
          refundRequestAmount: 999999,
          rightsMethod: 1,
          rightsNo: '123123423',
          rightsParentNo: '78970',
          rightsReasonDesc: i18n.t('Too expensive. Don\'t want it.'),
          rightsReasonType: 10,
          rightsStatus: 50,
          rightsStatusName: 'Completed',
          rightsType: 20,
          saasId: 123,
          shippingFee: 99,
          shippingFeeBear: 1,
          storeId: 123,
          storeName: i18n.t('Cmall flagship store'),
          uid: '123',
          updateTime: '1596524705613',
          userRightsStatus: 120,
          userRightsStatusDesc: i18n.t('The merchant has approved the refund. The refunds will take 3 business days to appear on your account.'),
          userRightsStatusName: 'Refunded',
          afterSaleRequireType: 'REFUND_MONEY',
          rightsImageUrls: [
            'https://cdn-we-retail.ym.tencent.com/tsr/goods/nz-09a.png',
            'https://cdn-we-retail.ym.tencent.com/tsr/goods/nz-09a.png',
            'https://cdn-we-retail.ym.tencent.com/tsr/goods/nz-09a.png',
            'https://cdn-we-retail.ym.tencent.com/tsr/goods/nz-09a.png',
          ],
        },
        rightsItem: [
          {
            actualPrice: 888,
            createTime: '1596524705613',
            disconutInfo: i18n.t('Buy now to save 100 Yuan'),
            goodsName: i18n.t('Xiaomi Phones'),
            goodsPictureUrl: 'https://cdn-we-retail.ym.tencent.com/tsr/goods/nz-09a.png',
            goodsViceType: 1,
            itemDiscountAmount: 123123,
            itemRefundAmount: 888,
            itemStatus: 2,
            itemTotalAmount: 9913,
            orderNo: '12312333',
            parentOrderNo: '1231234',
            rightsId: 423423,
            rightsNo: '112333',
            rightsParentNo: '345345',
            rightsQuantity: 12,
            saasId: 123,
            skuId: 812312,
            specInfo: [
              {
                specTitle: 'Test dr',
                specValues: 'Long test 1',
              },
              {
                specTitle: 'bwtgg01',
                specValues: 'eee',
              },
            ],
            updateTime: '1596524705613',
          },
          {
            actualPrice: 9999,
            createTime: '1596524705613',
            disconutInfo: i18n.t('Buy now to save 100 Yuan'),
            goodsName: i18n.t('Huawei Phones'),
            goodsPictureUrl:
              'https://cdn-we-retail.ym.tencent.com/tsr/goods/nz-09a.png',
            goodsViceType: 1,
            itemDiscountAmount: 123123,
            itemRefundAmount: 9999,
            itemStatus: 2,
            itemTotalAmount: 9913,
            orderNo: '12312333',
            parentOrderNo: '1231234',
            rightsId: 423423,
            rightsNo: '112333',
            rightsParentNo: '345345',
            rightsQuantity: 12,
            saasId: 123,
            skuId: 8123129,
            specInfo: [
              {
                specTitle: 'Test dr',
                specValues: 'Long test 1',
              },
              {
                specTitle: 'bwtgg01',
                specValues: 'eee',
              },
            ],
            updateTime: '1596524705613',
          },
        ],
        rightsRefund: {
          callbackTime: '1596524705613',
          channel: 'WeChat Pay',
          channelTrxNo: '123123',
          createTime: '1596524705613',
          refundDesc: i18n.t('The merchant has agreed to issue a refund.'),
          memo: 'No abstracts',
          refundAmount: 9999,
          refundStatus: 1,
          requestTime: '1596524705613',
          successTime: '1596524705613',
          traceNo: '123123',
          updateTime: '1596524705613',
        },
        logisticsVO: {
          logisticsType: 1,
          logisticsNo: 'SF2380380982034',
          logisticsStatus: null,
          logisticsCompanyCode: '',
          logisticsCompanyName: 'SF Express',
          receiverAddressId: '20',
          provinceCode: '440000',
          cityCode: '440300',
          countryCode: '440306',
          receiverProvince: 'Guangdong Province',
          receiverCity: 'Shenzhen',
          receiverCountry: 'Nanshan district',
          receiverArea: '',
          receiverAddress: 'Qingfeng Road Yulongwan',
          receiverPostCode: '',
          receiverLongitude: '113.880562',
          receiverLatitude: '22.56271',
          receiverIdentity: '88881046205',
          receiverPhone: '18371736717',
          receiverName: 'Jay Chou',
          expectArrivalTime: null,
          senderName: 'Andy Lau',
          senderPhone: '1273109238123',
          senderAddress: i18n.t('No. 108, Unit 4, Building 3, Dafeng Jiayuan, Changping District, Beijing'),
          sendTime: null,
          arrivalTime: null,
          nodes: [
            {
              title: 'Delivered',
              icon: 'https://cdn-we-retail.ym.tencent.com/tsr/icon/order.png',
              code: '200003',
              desc: i18n.t('The package has been delivered. Thank you for using SF Express.'),
              date: '2020-09-11 11:34:53',
            },
            {
              title: 'In transit',
              icon: 'https://cdn-we-retail.ym.tencent.com/tsr/icon/deliver.png',
              desc: i18n.t('Package arrived at Chengdu'),
              code: '200002',
              date: '2020-07-16 11:16:31',
            },
            {
              title: 'Shipped',
              icon: 'https://cdn-we-retail.ym.tencent.com/tsr/icon/deliver.png',
              desc: i18n.t('The package has been shipped by SF Express.'),
              date: '2020-07-16 11:16:21',
            },
          ],
        },
      },
      {
        buttonVOs: [
          {
            name: i18n.t('Fill in tracking number'),
            primary: false,
            type: 3,
          },
        ],
        saasId: '8888',
        storeId: '2591',
        uid: '88881046205',
        createTime: '1596524705613',
        rights: {
          rightsImageUrls: [
            'https://cdn-we-retail.ym.tencent.com/tsr/goods/nz-09a.png',
            'https://cdn-we-retail.ym.tencent.com/tsr/goods/nz-09a.png',
            'https://cdn-we-retail.ym.tencent.com/tsr/goods/nz-09a.png',
            'https://cdn-we-retail.ym.tencent.com/tsr/goods/nz-09a.png',
          ],
          bizRightsStatus: 1,
          bizRightsStatusName: i18n.t('Refund and return'),
          createTime: '1596524705613',
          orderNo: '12313123123',
          refundAmount: 99999,
          refundRequestAmount: 999999,
          rightsMethod: 1,
          rightsNo: '1231234231',
          rightsParentNo: '78970',
          rightsReasonDesc: i18n.t('Too expensive. Don\'t want it.'),
          rightsReasonType: 10,
          rightsStatus: 20,
          rightsStatusName: 'Approved',
          rightsType: 10,
          saasId: 123,
          shippingFee: 99,
          shippingFeeBear: 1,
          storeId: 123,
          storeName: i18n.t('Cmall flagship store'),
          uid: '123',
          updateTime: '1596524705613',
          userRightsStatus: 100,
          userRightsStatusDesc: i18n.t('The merchant has confirmed and will issue a refund in 1 hour.'),
          userRightsStatusName: i18n.t('The merchant has approved'),
        },
        rightsItem: [
          {
            actualPrice: 888,
            createTime: '1596524705613',
            disconutInfo: i18n.t('Buy now to save 100 Yuan'),
            goodsName: i18n.t('Xiaomi Phones'),
            goodsPictureUrl:
              'https://cdn-we-retail.ym.tencent.com/tsr/goods/nz-09a.png',
            goodsViceType: 1,
            itemDiscountAmount: 123123,
            itemRefundAmount: 888,
            itemStatus: 2,
            itemTotalAmount: 9913,
            orderNo: '12312333',
            parentOrderNo: '1231234',
            rightsId: 423423,
            rightsNo: '112333',
            rightsParentNo: '345345',
            rightsQuantity: 12,
            saasId: 123,
            skuId: 812312,
            specInfo: [
              {
                specTitle: 'Test dr',
                specValues: 'Long test 1',
              },
              {
                specTitle: 'bwtgg01',
                specValues: 'eee',
              },
            ],
            updateTime: '1596524705613',
          },
        ],
        rightsRefund: {
          callbackTime: '1596524705613',
          channel: 'WeChat Pay',
          channelTrxNo: '123123',
          createTime: '1596524705613',
          refundDesc: i18n.t('The merchant has agreed to issue a refund.'),
          memo: 'No abstracts',
          refundAmount: 9999,
          refundStatus: 1,
          requestTime: '1596524705613',
          successTime: '1596524705613',
          traceNo: '123123',
          updateTime: '1596524705613',
        },
        logisticsVO: {
          logisticsType: 1,
          logisticsNo: 'SA9208097023203',
          logisticsStatus: null,
          logisticsCompanyCode: '',
          logisticsCompanyName: 'STO Express ',
          receiverAddressId: '20',
          provinceCode: '440000',
          cityCode: '440300',
          countryCode: '440306',
          receiverProvince: 'Guangdong Province',
          receiverCity: 'Shenzhen',
          receiverCountry: 'Nanshan district',
          receiverArea: '',
          receiverAddress: 'Qingfeng Road Yulongwan',
          receiverPostCode: '',
          receiverLongitude: '113.880562',
          receiverLatitude: '22.56271',
          receiverIdentity: '88881046205',
          receiverPhone: '18371736717',
          receiverName: 'Jay Chou',
          expectArrivalTime: null,
          senderName: 'Andy Lau',
          senderPhone: '1273109238123',
          senderAddress: i18n.t('No. 108, Unit 4, Building 3, Dafeng Jiayuan, Changping District, Beijing City'),
          sendTime: null,
          arrivalTime: null,
        },
      },
      {
        buttonVOs: [
          {
            name: i18n.t('Cancel application'),
            primary: false,
            type: 2,
          },
        ],
        saasId: '8888',
        storeId: '2591',
        uid: '88881046205',
        createTime: '1596524705613',
        rights: {
          rightsImageUrls: [
            'https://cdn-we-retail.ym.tencent.com/tsr/goods/nz-09a.png',
            'https://cdn-we-retail.ym.tencent.com/tsr/goods/nz-09a.png',
            'https://cdn-we-retail.ym.tencent.com/tsr/goods/nz-09a.png',
            'https://cdn-we-retail.ym.tencent.com/tsr/goods/nz-09a.png',
          ],
          bizRightsStatus: 1,
          bizRightsStatusName: i18n.t('Refund and return'),
          createTime: '1596524705613',
          orderNo: '12313123123',
          refundAmount: 99999,
          refundRequestAmount: 999999,
          rightsMethod: 1,
          rightsNo: '1231234232',
          rightsParentNo: '78970',
          rightsReasonDesc: i18n.t('Too expensive. Don\'t want it.'),
          rightsReasonType: 10,
          rightsStatus: 60,
          rightsStatusName: 'Closed',
          rightsType: 10,
          saasId: 123,
          shippingFee: 99,
          shippingFeeBear: 1,
          storeId: 123,
          storeName: i18n.t('Cmall flagship store'),
          uid: '123',
          updateTime: '1596524705613',
          userRightsStatus: 100,
          userRightsStatusDesc: i18n.t('The merchant will process your refund request soon.'),
          userRightsStatusName: i18n.t('Waiting for merchant process'),
        },
        rightsItem: [
          {
            actualPrice: 888,
            createTime: '1596524705613',
            disconutInfo: i18n.t('Buy now to save 100 Yuan'),
            goodsName: i18n.t('Xiaomi Phones'),
            goodsPictureUrl:
              'https://cdn-we-retail.ym.tencent.com/tsr/goods/nz-09a.png',
            goodsViceType: 1,
            itemDiscountAmount: 123123,
            itemRefundAmount: 888,
            itemStatus: 2,
            itemTotalAmount: 9913,
            orderNo: '12312333',
            parentOrderNo: '1231234',
            rightsId: 423423,
            rightsNo: '112333',
            rightsParentNo: '345345',
            rightsQuantity: 12,
            saasId: 123,
            skuId: 812312,
            specInfo: [
              {
                specTitle: 'Test dr',
                specValues: 'Long test 1',
              },
              {
                specTitle: 'bwtgg01',
                specValues: 'eee',
              },
            ],
            updateTime: '1596524705613',
          },
        ],
        rightsRefund: {
          callbackTime: '1596524705613',
          channel: 'WeChat Pay',
          channelTrxNo: '123123',
          createTime: '1596524705613',
          memo: 'No abstracts',
          refundAmount: 9999,
          refundStatus: 1,
          requestTime: '1596524705613',
          successTime: '1596524705613',
          traceNo: '123123',
          updateTime: '1596524705613',
          refundDesc: i18n.t('Product does not match the description'),
        },
        logisticsVO: {
          logisticsType: 1,
          logisticsNo: 'SF9343043084',
          logisticsStatus: null,
          logisticsCompanyCode: '',
          logisticsCompanyName: 'SF Express',
          receiverAddressId: '20',
          provinceCode: '440000',
          cityCode: '440300',
          countryCode: '440306',
          receiverProvince: 'Guangdong Province',
          receiverCity: 'Shenzhen',
          receiverCountry: 'Nanshan district',
          receiverArea: '',
          receiverAddress: 'Qingfeng Road Yulongwan',
          receiverPostCode: '',
          receiverLongitude: '113.880562',
          receiverLatitude: '22.56271',
          receiverIdentity: '88881046205',
          receiverPhone: '18371736717',
          receiverName: 'Jay Chou',
          expectArrivalTime: null,
          senderName: 'Andy Lau',
          senderPhone: '1273109238123',
          senderAddress: i18n.t('No. 108, Unit 4, Building 3, Dafeng Jiayuan, Changping District, Beijing City'),
          sendTime: null,
          arrivalTime: null,
        },
      },
      {
        buttonVOs: [],
        saasId: '8888',
        storeId: '2591',
        uid: '88881046205',
        createTime: '1596524705613',
        refundMethodList: [
          {
            refundMethodAmount: 99999,
            refundMethodName: 'WeChat Pay',
          },
          {
            refundMethodAmount: 100000,
            refundMethodName: i18n.t('Credit or debit card'),
          },
        ],
        rights: {
          bizRightsStatus: 1,
          bizRightsStatusName: i18n.t('Refund and return'),
          createTime: '1596524705613',
          orderNo: '12313123123',
          refundAmount: 99999,
          refundRequestAmount: 999999,
          rightsMethod: 1,
          rightsNo: '1231234233',
          rightsParentNo: '78970',
          rightsReasonDesc: i18n.t('Too expensive. Don\'t want it.'),
          rightsReasonType: 10,
          rightsStatus: 50,
          rightsStatusName: 'Completed',
          rightsType: 10,
          saasId: 123,
          shippingFee: 99,
          shippingFeeBear: 1,
          storeId: 123,
          storeName:i18n.t('Cmall flagship store-Cmall flagship store-Cmall flagship store'),
          uid: '123',
          updateTime: '1596524705613',
          userRightsStatus: 160,
          userRightsStatusDesc: 'The refund/after-sales service has completed',
          userRightsStatusName: 'Completed',
        },
        rightsItem: [
          {
            actualPrice: 888,
            createTime: '1596524705613',
            disconutInfo: i18n.t('Buy now to save 100 Yuan'),
            goodsName: i18n.t('Xiaomi Phones'),
            goodsPictureUrl:
              'https://cdn-we-retail.ym.tencent.com/tsr/goods/nz-09a.png',
            goodsViceType: 1,
            itemDiscountAmount: 123123,
            itemRefundAmount: 888,
            itemStatus: 2,
            itemTotalAmount: 9913,
            orderNo: '12312333',
            parentOrderNo: '1231234',
            rightsId: 423423,
            rightsNo: '112333',
            rightsParentNo: '345345',
            rightsQuantity: 12,
            saasId: 123,
            skuId: 812312,
            specInfo: [
              {
                specTitle: 'Test dr',
                specValues: 'Long test 1',
              },
              {
                specTitle: 'bwtgg01',
                specValues: 'eee',
              },
            ],
            updateTime: '1596524705613',
          },
        ],
        rightsRefund: {
          callbackTime: '1596524705613',
          channel: 'WeChat Pay',
          channelTrxNo: '123123',
          createTime: '1596524705613',
          memo: 'No abstracts',
          refundAmount: 9999,
          refundStatus: 1,
          requestTime: '1596524705613',
          successTime: '1596524705613',
          traceNo: '123123',
          updateTime: '1596524705613',
        },
        logisticsVO: {
          logisticsType: 1,
          logisticsNo: '',
          logisticsStatus: null,
          logisticsCompanyCode: '',
          logisticsCompanyName: '',
          receiverAddressId: '20',
          provinceCode: '440000',
          cityCode: '440300',
          countryCode: '440306',
          receiverProvince: 'Guangdong Province',
          receiverCity: 'Shenzhen',
          receiverCountry: 'Nanshan district',
          receiverArea: '',
          receiverAddress: 'Qingfeng Road Yulongwan',
          receiverPostCode: '',
          receiverLongitude: '113.880562',
          receiverLatitude: '22.56271',
          receiverIdentity: '88881046205',
          receiverPhone: '18371736717',
          receiverName: 'Jay Chou',
          expectArrivalTime: null,
          senderName: 'Andy Lau',
          senderPhone: '1273109238123',
          senderAddress: i18n.t('No. 108, Unit 4, Building 3, Dafeng Jiayuan, Changping District, Beijing City'),
          sendTime: null,
          arrivalTime: null,
        },
      },
      {
        buttonVOs: [
          {
            name: i18n.t('Modify tracking number'),
            primary: false,
            type: 4,
          },
        ],
        saasId: '8888',
        storeId: '2591',
        uid: '88881046205',
        createTime: '1596524705613',
        rights: {
          bizRightsStatus: 1,
          bizRightsStatusName: i18n.t('Refund and return'),
          createTime: '1596524705613',
          orderNo: '12313123123',
          refundAmount: 99999,
          refundRequestAmount: 999999,
          rightsMethod: 1,
          rightsNo: '1231234234',
          rightsParentNo: '78970',
          rightsReasonDesc: i18n.t('Too expensive. Don\'t want it.'),
          rightsReasonType: 10,
          rightsStatus: 20,
          rightsStatusName: 'Approved',
          rightsType: 10,
          saasId: 123,
          shippingFee: 99,
          shippingFeeBear: 1,
          storeId: 123,
          storeName: i18n.t('Cmall flagship store'),
          uid: '123',
          updateTime: '1596524705613',
          userRightsStatus: 1,
          userRightsStatusDesc: i18n.t('The merchant has confirmed and will issue a refund in 1 hour.'),
          userRightsStatusName: i18n.t('The merchant has approved'),
        },
        rightsItem: [
          {
            actualPrice: 888,
            createTime: '1596524705613',
            disconutInfo: i18n.t('Buy now to save 100 Yuan'),
            goodsName: i18n.t('Xiaomi Phones'),
            goodsPictureUrl:
              'https://cdn-we-retail.ym.tencent.com/tsr/goods/nz-09a.png',
            goodsViceType: 1,
            itemDiscountAmount: 123123,
            itemRefundAmount: 888,
            itemStatus: 2,
            itemTotalAmount: 9913,
            orderNo: '12312333',
            parentOrderNo: '1231234',
            rightsId: 423423,
            rightsNo: '112333',
            rightsParentNo: '345345',
            rightsQuantity: 12,
            saasId: 123,
            skuId: 812312,
            specInfo: [
              {
                specTitle: 'Test dr',
                specValues: 'Long test 1',
              },
              {
                specTitle: 'bwtgg01',
                specValues: 'eee',
              },
            ],
            updateTime: '1596524705613',
          },
        ],
        rightsRefund: {
          callbackTime: '1596524705613',
          channel: 'WeChat Pay',
          channelTrxNo: '123123',
          createTime: '1596524705613',
          memo: 'No abstracts',
          refundAmount: 9999,
          refundStatus: 1,
          requestTime: '1596524705613',
          successTime: '1596524705613',
          traceNo: '123123',
          updateTime: '1596524705613',
        },
        logisticsVO: {
          logisticsType: 1,
          logisticsNo: '80900909',
          logisticsStatus: null,
          logisticsCompanyCode: '0004',
          logisticsCompanyName: 'SF Express',
          remark: 'Product quality issue',
          receiverAddressId: '20',
          provinceCode: '440000',
          cityCode: '440300',
          countryCode: '440306',
          receiverProvince: 'Guangdong Province',
          receiverCity: 'Shenzhen',
          receiverCountry: 'Nanshan district',
          receiverArea: '',
          receiverAddress: 'Qingfeng Road Yulongwan',
          receiverPostCode: '',
          receiverLongitude: '113.880562',
          receiverLatitude: '22.56271',
          receiverIdentity: '88881046205',
          receiverPhone: '18371736717',
          receiverName: 'Jay Chou',
          expectArrivalTime: null,
          senderName: 'Andy Lau',
          senderPhone: '1273109238123',
          senderAddress: i18n.t('No. 108, Unit 4, Building 3, Dafeng Jiayuan, Changping District, Beijing City'),
          sendTime: null,
          arrivalTime: null,
        },
      },
      {
        buttonVOs: [
          {
            name: i18n.t('Cancel application'),
            primary: false,
            type: 2,
          },
        ],
        saasId: '8888',
        storeId: '2591',
        uid: '88881046205',
        createTime: '1596524705613',
        rights: {
          bizRightsStatus: 1,
          bizRightsStatusName: i18n.t('Refund and return'),
          createTime: '1596524705613',
          orderNo: '12313123123',
          refundAmount: 99999,
          refundRequestAmount: 999999,
          rightsMethod: 1,
          rightsNo: '1231234235',
          rightsParentNo: '78970',
          rightsReasonDesc: i18n.t('Buy now to save 100 Yuan'),
          rightsReasonType: 10,
          rightsStatus: 10,
          rightsStatusName: 'Pending',
          rightsType: 10,
          saasId: 123,
          shippingFee: 99,
          shippingFeeBear: 1,
          storeId: 123,
          storeName:
            'Cmall flagship store-Cmall flagship store-Cmall flagship store-Cmall flagship store-Cmall flagship store-Cmall flagship store-Cmall flagship store',
          uid: '123',
          updateTime: '1596524705613',
          userRightsStatus: 1,
          userRightsStatusDesc:
            'The merchant will process within 24 hours. If the merchant has not processed after 24 hours, the system will automatically approve the request.',
          userRightsStatusName: 'Waiting for the merchant process',
        },
        rightsItem: [
          {
            actualPrice: 888,
            createTime: '1596524705613',
            disconutInfo: i18n.t('Buy now to save 100 Yuan'),
            goodsName:
              'Xiaomi Phones-Xiaomi Phones-Xiaomi Phones-Xiaomi Phones-Xiaomi Phones-Xiaomi Phones-Xiaomi Phones-Xiaomi Phones-Xiaomi Phones-Xiaomi Phones-Xiaomi Phones-Xiaomi Phones-Xiaomi Phones-Xiaomi Phones-Xiaomi Phones-Xiaomi Phones-Xiaomi Phones',
            goodsPictureUrl:
              'https://cdn-we-retail.ym.tencent.com/tsr/goods/nz-09a.png',
            goodsViceType: 1,
            itemDiscountAmount: 123123,
            itemRefundAmount: 888,
            itemStatus: 2,
            itemTotalAmount: 9913,
            orderNo: '12312333',
            parentOrderNo: '1231234',
            rightsId: 423423,
            rightsNo: '112333',
            rightsParentNo: '345345',
            rightsQuantity: 12,
            saasId: 123,
            skuId: 812312,
            specInfo: [
              {
                specTitle: 'Test dr',
                specValues: 'Long test 1',
              },
              {
                specTitle: 'bwtgg01',
                specValues: 'eee',
              },
            ],
            updateTime: '1596524705613',
          },
        ],
        rightsRefund: {
          callbackTime: '1596524705613',
          channel: 'WeChat Pay',
          channelTrxNo: '123123',
          createTime: '1596524705613',
          memo: 'No abstracts',
          refundAmount: 9999,
          refundStatus: 1,
          requestTime: '1596524705613',
          successTime: '1596524705613',
          traceNo: '123123',
          updateTime: '1596524705613',
        },
        logisticsVO: {
          logisticsType: 1,
          logisticsNo: '',
          logisticsStatus: null,
          logisticsCompanyCode: '',
          logisticsCompanyName: '',
          receiverAddressId: '20',
          provinceCode: '440000',
          cityCode: '440300',
          countryCode: '440306',
          receiverProvince: 'Guangdong Province',
          receiverCity: 'Shenzhen',
          receiverCountry: 'Nanshan district',
          receiverArea: '',
          receiverAddress: 'Qingfeng Road Yulongwan',
          receiverPostCode: '',
          receiverLongitude: '113.880562',
          receiverLatitude: '22.56271',
          receiverIdentity: '88881046205',
          receiverPhone: '18371736717',
          receiverName: 'Jay Chou',
          expectArrivalTime: null,
          senderName: 'Andy Lau',
          senderPhone: '1273109238123',
          senderAddress: i18n.t('No. 108, Unit 4, Building 3, Dafeng Jiayuan, Changping District, Beijing City'),
          sendTime: null,
          arrivalTime: null,
        },
      },
      {
        buttonVOs: [
          {
            name: i18n.t('Modify tracking number'),
            primary: false,
            type: 4,
          },
        ],
        saasId: '8888',
        storeId: '2591',
        uid: '88881046205',
        createTime: '1596524705613',
        rights: {
          bizRightsStatus: 1,
          bizRightsStatusName: i18n.t('Refund and return'),
          createTime: '1596524705613',
          orderNo: '12313123123',
          refundAmount: 99999,
          refundRequestAmount: 999999,
          rightsMethod: 1,
          rightsNo: '1231234236',
          rightsParentNo: '78970',
          rightsReasonDesc: i18n.t('Buy now to save 100 Yuan'),
          rightsReasonType: 10,
          rightsStatus: 20,
          rightsStatusName: 'Approved',
          rightsType: 10,
          saasId: 123,
          shippingFee: 99,
          shippingFeeBear: 1,
          storeId: 123,
          storeName: i18n.t('Cmall flagship store'),
          uid: '123',
          updateTime: '1596524705613',
          userRightsStatus: 1,
          userRightsStatusDesc: i18n.t('The merchant has confirmed and will issue a refund in 1 hour.'),
          userRightsStatusName: i18n.t('The merchant has approved'),
        },
        rightsItem: [
          {
            actualPrice: 888,
            createTime: '1596524705613',
            disconutInfo: i18n.t('Buy now to save 100 Yuan'),
            goodsName: i18n.t('Xiaomi Phones'),
            goodsPictureUrl:
              'https://cdn-we-retail.ym.tencent.com/tsr/goods/nz-09a.png',
            goodsViceType: 1,
            itemDiscountAmount: 123123,
            itemRefundAmount: 888,
            itemStatus: 2,
            itemTotalAmount: 9913,
            orderNo: '12312333',
            parentOrderNo: '1231234',
            rightsId: 423423,
            rightsNo: '112333',
            rightsParentNo: '345345',
            rightsQuantity: 12,
            saasId: 123,
            skuId: 812312,
            specInfo: [
              {
                specTitle: 'Test dr ',
                specValues: 'Long test 1',
              },
              {
                specTitle: 'bwtgg01',
                specValues: 'eee',
              },
            ],
            updateTime: '1596524705613',
          },
        ],
        rightsRefund: {
          callbackTime: '1596524705613',
          channel: 'WeChat Pay',
          channelTrxNo: '123123',
          createTime: '1596524705613',
          memo: 'No abstracts',
          refundAmount: 9999,
          refundStatus: 1,
          requestTime: '1596524705613',
          successTime: '1596524705613',
          traceNo: '123123',
          updateTime: '1596524705613',
        },
        logisticsVO: {
          logisticsType: 1,
          logisticsNo: '90900808',
          logisticsStatus: null,
          logisticsCompanyCode: '0002',
          logisticsCompanyName: 'STO Express',
          remark: 'Product quality issue',
          receiverAddressId: '20',
          provinceCode: '440000',
          cityCode: '440300',
          countryCode: '440306',
          receiverProvince: 'Guangdong Province',
          receiverCity: 'Shenzhen',
          receiverCountry: 'Nanshan district',
          receiverArea: '',
          receiverAddress: 'Qingfeng Road Yulongwan',
          receiverPostCode: '',
          receiverLongitude: '113.880562',
          receiverLatitude: '22.56271',
          receiverIdentity: '88881046205',
          receiverPhone: '18371736717',
          receiverName: 'Jay Chou',
          expectArrivalTime: null,
          senderName: 'Andy Lau',
          senderPhone: '1273109238123',
          senderAddress: i18n.t('No. 108, Unit 4, Building 3, Dafeng Jiayuan, Changping District, Beijing City'),
          sendTime: null,
          arrivalTime: null,
        },
      },
      {
        buttonVOs: [
          {
            name: i18n.t('Fill in tracking number'),
            primary: false,
            type: 3,
          },
        ],
        saasId: '8888',
        storeId: '2591',
        uid: '88881046205',
        createTime: '1596524705613',
        rights: {
          bizRightsStatus: 1,
          bizRightsStatusName: i18n.t('Refund and return'),
          createTime: '1596524705613',
          orderNo: '12313123123',
          refundAmount: 99999,
          refundRequestAmount: 999999,
          rightsMethod: 1,
          rightsNo: '1231234237',
          rightsParentNo: '78970',
          rightsReasonDesc: i18n.t('Too expensive. Don\'t want it.'),
          rightsReasonType: 10,
          rightsStatus: 20,
          rightsStatusName: 'Approved',
          rightsType: 10,
          saasId: 123,
          shippingFee: 99,
          shippingFeeBear: 1,
          storeId: 123,
          storeName: i18n.t('Cmall flagship store'),
          uid: '123',
          updateTime: '1596524705613',
          userRightsStatus: 1,
          userRightsStatusDesc: i18n.t('The merchant has confirmed and will issue a refund in 1 hour.'),
          userRightsStatusName: i18n.t('The merchant has approved'),
        },
        rightsItem: [
          {
            actualPrice: 888,
            createTime: '1596524705613',
            disconutInfo: i18n.t('Buy now to save 100 Yuan'),
            goodsName: i18n.t('Xiaomi Phones'),
            goodsPictureUrl: 'https://cdn-we-retail.ym.tencent.com/tsr/goods/nz-09a.png',
            goodsViceType: 1,
            itemDiscountAmount: 123123,
            itemRefundAmount: 888,
            itemStatus: 2,
            itemTotalAmount: 9913,
            orderNo: '12312333',
            parentOrderNo: '1231234',
            rightsId: 423423,
            rightsNo: '112333',
            rightsParentNo: '345345',
            rightsQuantity: 12,
            saasId: 123,
            skuId: 812312,
            specInfo: [
              {
                specTitle: 'Test dr ',
                specValues: 'Long test 1',
              },
              {
                specTitle: 'bwtgg01',
                specValues: 'eee',
              },
            ],
            updateTime: '1596524705613',
          },
        ],
        rightsRefund: {
          callbackTime: '1596524705613',
          channel: 'WeChat Pay',
          channelTrxNo: '123123',
          createTime: '1596524705613',
          memo: 'No abstracts',
          refundAmount: 9999,
          refundStatus: 1,
          requestTime: '1596524705613',
          successTime: '1596524705613',
          traceNo: '123123',
          updateTime: '1596524705613',
        },
        logisticsVO: {
          logisticsType: 1,
          logisticsNo: '',
          logisticsStatus: null,
          logisticsCompanyCode: '',
          logisticsCompanyName: '',
          receiverAddressId: '20',
          provinceCode: '440000',
          cityCode: '440300',
          countryCode: '440306',
          receiverProvince: 'Guangdong Province',
          receiverCity: 'Shenzhen',
          receiverCountry: 'Nanshan district',
          receiverArea: '',
          receiverAddress: 'Qingfeng Road Yulongwan',
          receiverPostCode: '',
          receiverLongitude: '113.880562',
          receiverLatitude: '22.56271',
          receiverIdentity: '88881046205',
          receiverPhone: '18371736717',
          receiverName: 'Jay Chou',
          expectArrivalTime: null,
          senderName: 'Andy Lau',
          senderPhone: '1273109238123',
          senderAddress: i18n.t('No. 108, Unit 4, Building 3, Dafeng Jiayuan, Changping District, Beijing City'),
          sendTime: null,
          arrivalTime: null,
        },
      },
      {
        buttonVOs: [
          {
            name: i18n.t('Cancel application'),
            primary: false,
            type: 2,
          },
        ],
        saasId: '8888',
        storeId: '2591',
        uid: '88881046205',
        createTime: '1596524705613',
        rights: {
          bizRightsStatus: 1,
          bizRightsStatusName: i18n.t('Refund and return'),
          createTime: '1596524705613',
          orderNo: '123131231238',
          refundAmount: 99999,
          refundRequestAmount: 999999,
          rightsMethod: 1,
          rightsNo: '1231234238',
          rightsParentNo: '78970',
          rightsReasonDesc: i18n.t('Too expensive. Don\'t want it.'),
          rightsReasonType: 10,
          rightsStatus: 20,
          rightsStatusName: 'Approved',
          rightsType: 10,
          saasId: 123,
          shippingFee: 99,
          shippingFeeBear: 1,
          storeId: 123,
          storeName: i18n.t('Cmall flagship store'),
          uid: '123',
          updateTime: '1596524705613',
          userRightsStatus: 1,
          userRightsStatusDesc: i18n.t('The merchant has confirmed and will issue a refund in 1 hour.'),
          userRightsStatusName: i18n.t('The merchant has approved'),
        },
        rightsItem: [
          {
            actualPrice: 888,
            createTime: '1596524705613',
            disconutInfo: i18n.t('Buy now to save 100 Yuan'),
            goodsName: i18n.t('Xiaomi Phones'),
            goodsPictureUrl:
              'https://cdn-we-retail.ym.tencent.com/tsr/goods/nz-09a.png',
            goodsViceType: 1,
            itemDiscountAmount: 123123,
            itemRefundAmount: 888,
            itemStatus: 2,
            itemTotalAmount: 9913,
            orderNo: '12312333',
            parentOrderNo: '1231234',
            rightsId: 423423,
            rightsNo: '112333',
            rightsParentNo: '345345',
            rightsQuantity: 12,
            saasId: 123,
            skuId: 812312,
            specInfo: [
              {
                specTitle: 'Test dr ',
                specValues: 'Long test 1',
              },
              {
                specTitle: 'bwtgg01',
                specValues: 'eee',
              },
            ],
            updateTime: '1596524705613',
          },
        ],
        rightsRefund: {
          callbackTime: '1596524705613',
          channel: 'WeChat Pay',
          channelTrxNo: '123123',
          createTime: '1596524705613',
          memo: 'No abstracts',
          refundAmount: 9999,
          refundStatus: 1,
          requestTime: '1596524705613',
          successTime: '1596524705613',
          traceNo: '123123',
          updateTime: '1596524705613',
        },
        logisticsVO: {
          logisticsType: 1,
          logisticsNo: '',
          logisticsStatus: null,
          logisticsCompanyCode: '',
          logisticsCompanyName: '',
          receiverAddressId: '20',
          provinceCode: '440000',
          cityCode: '440300',
          countryCode: '440306',
          receiverProvince: 'Guangdong Province',
          receiverCity: 'Shenzhen',
          receiverCountry: 'Nanshan district',
          receiverArea: '',
          receiverAddress: 'Qingfeng Road Yulongwan',
          receiverPostCode: '',
          receiverLongitude: '113.880562',
          receiverLatitude: '22.56271',
          receiverIdentity: '88881046205',
          receiverPhone: '18371736717',
          receiverName: 'Jay Chou',
          expectArrivalTime: null,
          senderName: 'Andy Lau',
          senderPhone: '1273109238123',
          senderAddress: i18n.t('No. 108, Unit 4, Building 3, Dafeng Jiayuan, Changping District, Beijing City'),
          sendTime: null,
          arrivalTime: null,
        },
      },
      {
        buttonVOs: [
          {
            name: i18n.t('Fill in tracking number'),
            primary: false,
            type: 3,
          },
        ],
        saasId: '8888',
        storeId: '2591',
        uid: '88881046205',
        createTime: '1596524705613',
        rights: {
          bizRightsStatus: 1,
          bizRightsStatusName: i18n.t('Refund and return'),
          createTime: '1596524705613',
          orderNo: '12313123123',
          refundAmount: 99999,
          refundRequestAmount: 999999,
          rightsMethod: 1,
          rightsNo: '1231234239',
          rightsParentNo: '78970',
          rightsReasonDesc: i18n.t('Too expensive. Don\'t want it.'),
          rightsReasonType: 10,
          rightsStatus: 20,
          rightsStatusName: 'Approved',
          rightsType: 10,
          saasId: 123,
          shippingFee: 99,
          shippingFeeBear: 1,
          storeId: 123,
          storeName: i18n.t('Cmall flagship store'),
          uid: '123',
          updateTime: '1596524705613',
          userRightsStatus: 1,
          userRightsStatusDesc: i18n.t('The merchant has confirmed and will issue a refund in 1 hour.'),
          userRightsStatusName: i18n.t('The merchant has approved'),
        },
        rightsItem: [
          {
            actualPrice: 888,
            createTime: '1596524705613',
            disconutInfo: i18n.t('Buy now to save 100 Yuan'),
            goodsName:
              'Xiaomi Phones-Xiaomi Phones-Xiaomi Phones-Xiaomi Phones-Xiaomi Phones-Xiaomi Phones-Xiaomi Phones-Xiaomi Phones-Xiaomi Phones-Xiaomi Phones-Xiaomi Phones-Xiaomi Phones',
            goodsPictureUrl:
              'https://cdn-we-retail.ym.tencent.com/tsr/goods/nz-09a.png',
            goodsViceType: 1,
            itemDiscountAmount: 123123,
            itemRefundAmount: 888,
            itemStatus: 2,
            itemTotalAmount: 9913,
            orderNo: '12312333',
            parentOrderNo: '1231234',
            rightsId: 423423,
            rightsNo: '112333',
            rightsParentNo: '345345',
            rightsQuantity: 12,
            saasId: 123,
            skuId: 812312,
            specInfo: [
              {
                specTitle: 'Test dr ',
                specValues: 'Long test 1',
              },
              {
                specTitle: 'bwtgg01',
                specValues: 'eee',
              },
            ],
            updateTime: '1596524705613',
          },
        ],
        rightsRefund: {
          callbackTime: '1596524705613',
          channel: 'WeChat Pay',
          channelTrxNo: '123123',
          createTime: '1596524705613',
          memo: 'No abstracts',
          refundAmount: 9999,
          refundStatus: 1,
          requestTime: '1596524705613',
          successTime: '1596524705613',
          traceNo: '123123',
          updateTime: '1596524705613',
        },
        logisticsVO: {
          logisticsType: 1,
          logisticsNo: '',
          logisticsStatus: null,
          logisticsCompanyCode: '',
          logisticsCompanyName: '',
          receiverAddressId: '20',
          provinceCode: '440000',
          cityCode: '440300',
          countryCode: '440306',
          receiverProvince: 'Guangdong Province',
          receiverCity: 'Shenzhen',
          receiverCountry: 'Nanshan district',
          receiverArea: '',
          receiverAddress: 'Qingfeng Road Yulongwan',
          receiverPostCode: '',
          receiverLongitude: '113.880562',
          receiverLatitude: '22.56271',
          receiverIdentity: '88881046205',
          receiverPhone: '18371736717',
          receiverName: 'Jay Chou',
          expectArrivalTime: null,
          senderName: 'Andy Lau',
          senderPhone: '1273109238123',
          senderAddress: i18n.t('No. 108, Unit 4, Building 3, Dafeng Jiayuan, Changping District, Beijing City'),
          sendTime: null,
          arrivalTime: null,
        },
      },
    ],
  },
  code: 'Success',
  msg: null,
  requestId: mockReqId(),
  clientIp: mockIp(),
  rt: 79,
  success: true,
};

export function getRightsList({ parameter: { afterServiceStatus, pageNum } }) {
  const _resq = JSON.parse(JSON.stringify(resp));
  if (pageNum > 3) _resq.data.dataList = [];
  if (afterServiceStatus > -1) {
    _resq.data.dataList = _resq.data.dataList.filter(
      (item) => item.rights.rightsStatus === afterServiceStatus,
    );
  }
  return Promise.resolve(_resq);
}
